spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/movie?createDatabaseIfNotExist=true
    # Movie schema create if not exist movie schema
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # change code location
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # ??? ??
        format_sql: true  # Easy to view sql
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: verify0213@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server.port: 8080
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
