spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
#    url: jdbc:mysql://localhost:3306/movie?createDatabaseIfNotExist=true # 개발시 코드.
#    username: root
#    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://movie-db.chqc8i4es01s.ap-northeast-2.rds.amazonaws.com/movie
    username: root
    password: pepsi1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # change code location
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # ??? ??
        # format_sql: true  # Easy to view sql
  data:
#    redis: # 개발용
#      host: localhost
#      port: 6379
    redis:
      host: master.movie-redis.3cwcca.apn2.cache.amazonaws.com
      port: 6379
      timeout: 5000ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: verify0213@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server.port: 8080
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method

api:
  KOFIC_API_KEY: "65a8c2b9d77ff46a7957c24a83a213a9"
  TMDB_API_KEY: "f613772b7ede7a7150acb1592fbb88e0"
  RECOMMEND_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZTg3ZjQ0N2MyMDc4ZDc3ZjY2YzRkMzliODZmYzZkYSIsIm5iZiI6MTc0MTI2ODc3MS4yODMsInN1YiI6IjY3YzlhNzIzMmU3MjkxMzA2ZjI0YjZmOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.eM77PQpNscHBlfxnxEEAIFu1_jvpUos4SOCyo_HVVXk"